### ISSUE TITLE
Outlook Version Issue

### ISSUE THREAD

**Issue by JaySmith-zz** [JaySmith/Marble#6]
Getting error when office version is not the same as what it was compiled against.

**Comment by DanielJGoodwin** [comment]
The way we were going to resolve this issue is to remove reference to Outlook.Interop and use NetOffice to handle multiple MS Office versions. However, NetOffice has some issues with their NetOffice.OutlookAPI.  Until these issues are resolved, we'll continue to compile against Office 2010, which seems to be forward compatible with Office 2013.  We do not think this will work correctly with Office 2003, or 2007.  Testing is still needed.
